### ISSUE TITLE
sqlalchemy.exc.TimeoutError

### ISSUE THREAD

**Issue by alexgheorghiu** [alexgheorghiu/amalgam#2]
![image](https://user-images.githubusercontent.com/1814282/113386211-6b525c00-9392-11eb-80bd-b887b9feca86.png)

sqlalchemy.exc.TimeoutError

sqlalchemy.exc.TimeoutError: QueuePool limit of size 40 overflow 0 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/13/3o7r)
Traceback (most recent call last)

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2464, in __call__

     

        def __call__(self, environ, start_response):

            """The WSGI server calls the Flask application object as the

            WSGI application. This calls :meth:`wsgi_app` which can be

            wrapped to applying middleware."""

            return self.wsgi_app(environ, start_response)

     

        def __repr__(self):

            return "<%s %r>" % (self.__class__.__name__, self.name)

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app

    response = self.handle_exception(e)

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app

    response = self.full_dispatch_request()

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request

    rv = self.dispatch_request()

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/root/amalgam/amalgam/app.py", line 56, in wrap

    return f(*args, **kwargs)

    File "/root/amalgam/amalgam/app.py", line 115, in home

    user = delegate.user_get_by_id(session['user_id'])

    File "/root/amalgam/amalgam/delegate.py", line 308, in user_get_by_id

    user = session.query(User).get(id)

    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 1018, in get

    return self._get_impl(ident, loading.load_on_pk_identity)

    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 1135, in _get_impl

    return db_load_fn(self, primary_key_identity)

    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/loading.py", line 286, in load_on_pk_identity

    return q.one()

    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3490, in one

    ret = self.one_or_none()

    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none

    ret = list(self)

    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3535, in __iter__

    return self._execute_and_instances(context)

    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3556, in _execute_and_instances

    conn = self._get_bind_args(

    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3571, in _get_bind_args

    return fn(

    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session

    conn = self.session.connection(**kw)

    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1138, in connection

    return self._connection_for_bind(

    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1146, in _connection_for_bind

    return self.transaction._connection_for_bind(

    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind

    conn = bind._contextual_connect()

    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect

    self._wrap_pool_connect(self.pool.connect, None),

    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect

    return fn()

    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 364, in connect

    return _ConnectionFairy._checkout(self)

    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 778, in _checkout

    fairy = _ConnectionRecord.checkout(pool)

    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 495, in checkout

    rec = pool._do_get()

    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/impl.py", line 128, in _do_get

    raise exc.TimeoutError(

    sqlalchemy.exc.TimeoutError: QueuePool limit of size 40 overflow 0 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/13/3o7r)

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

    dump() shows all variables in the frame
    dump(obj) dumps all that's known about the object

**Comment by alexgheorghiu** [comment]
You can replicate this by running 4-5 crawls on "One" site and very soon the upper capacity of pool will be reached.

**Comment by alexgheorghiu** [comment]
Fixed with d4d4c81feb2987f53d95fe337f0770da41defbe0
